### ISSUE TITLE
Heal macro bug.

### ISSUE THREAD

**Issue by scriptgaming** [Romain-P/Ewt-Scripts#3]
player hp under 80% wont cast flash heal if target is player.
its will spam BINDING_HEAL on urself but you cant cast BINDING_HEAL due to the target is player.
i fix like this,  

            local id = PriestSpells.FLASH_HEAL

            if HealthIsUnder(player, 80)
                    and not UnitIsUnit(unit, player) then -- my fixed
                    -- and unit ~= player then
                id = PriestSpells.BINDING_HEAL
            end

            Cast(id, unit, ally)

**Comment by Romain-P** [comment]
You didn't read as well the script, I already check if unit is player ;)
