### ISSUE TITLE
Ret profile

### ISSUE THREAD

**Issue by Romain-P** [Romain-P/Ewt-Scripts#5]
Add multiple options:

> Few things I've noticed:
> 
> It uses Divine Storm when I am no where near the target and is the first spell it uses. Would obviously be better if it used a Judgement first unless in range.
> 
> Doesn't seem to auto target when in range?
> 
> Is there anyway to make the rotation and the above happen automatically? That's why I like PQR, I can just run in and it auto targets, buffs and does the rotation with a Hammer of Wrath to finish. Also snipes players I'm not focusing with Hammer of Wrath. I always get top of the leaderboard in WSG with this. I just feel the defence side is not so good, it casts sacred shield but doesn't seem to cleanse too well or use Divine Shield and Lay of Hands etc. Trinket would be amazing feature if possible for PVP when movement impaired.
> 
> Basically I use the moving cast feature in EWT with PQR which frees up my fingers to move around instead so I don't have to be mashing buttons for abilities while stood still. Hope that makes sense? Gives me a big advantage, good for kiting!

**Comment by Fot3k** [comment]
So is this something you are able to implement? Wasn't sure where we going from the previous conversation.

Auto Target.
Auto Buff PVE/PVP.
Auto Rotation based on situation.
Auto Dispel/Cleanse/Bubble/Heal.
Hammer of Wrath when below 20% HP.

Are the basic features I would love and would replace PQR to be an amazing tool.

Thanks :)

**Comment by Romain-P** [comment]
Ofc it's possible,
It will be easier to implement it if I can write you and get an answer faster, somewhere else that a github issue, do u have smtg or should I create a slack?

**Comment by Romain-P** [comment]
https://join.slack.com/t/ewt-scripts/shared_invite/enQtNDE4MDczOTUxNDYwLTk2ZGRjOTQ4NDA3OGE1YmQ4MTZiOGM3ZDhlN2E4ODUxZTgwZDBmMjUwOTk5Y2IxN2RhNTY4MTMzYzgyYWI4M2E

**Comment by Hydracs** [comment]
Will you be working on a more polish ret paladin script? Is it possible to implment  an auto fear Gargoyle and warlock pets with Turn Evil?

**Comment by Romain-P** [comment]
Why not yes
